# Nom de l'application
spring.application.name=course_management

# Configuration de la source de données
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/course?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

### JPA / HIBERNATE ###
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect

# Configuration des ressources statiques
spring.web.resources.static-locations=classpath:/uploads/
spring.web.resources.cache.cachecontrol.no-cache=true

# Configuration du serveur principal
server.port=9696

# Configuration du serveur pour l'Actuator (liveness et readiness probes)
management.server.port=8086
management.endpoints.web.exposure.include=health,info

# Configuration pour les métriques Prometheus
management.metrics.export.prometheus.enabled=true
