apiVersion: v1
kind: ConfigMap
metadata:
  name: java-app-config
  namespace: course-management-app
data:
  application.properties: |
    spring.datasource.url=jdbc:mysql://mysql-service:3306/course
    spring.datasource.username=rim
    spring.datasource.password=123
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=true
