apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc  # Nom du PVC
spec:
  accessModes:
    - ReadWriteOnce  # Le volume peut être monté en lecture-écriture par un seul nœud
  resources:
    requests:
      storage: 1Gi  # Demande de 1 Go de stockage
